/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.laberinto1.Vista;
import java.awt.event.ActionListener;
import ucr.ac.cr.tm2100.g3.laberinto1.Modelo.Controlador;

/**
 *
 * @author carlo
 */
public class GUIHistoria extends javax.swing.JFrame {

    /**
     * Creates new form GUIHistoria
     */
    public GUIHistoria() {
        initComponents();
        setTitle("The Sin Of The Gods");
        setLocationRelativeTo(null);
        setResizable(false);
    }
        public void escuchar(ActionListener controlador) {
       btnSalirhistoria.addActionListener(controlador);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalirhistoria = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalirhistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnRegresar.jpg"))); // NOI18N
        btnSalirhistoria.setText("Salir de Historia");
        btnSalirhistoria.setBorderPainted(false);
        btnSalirhistoria.setContentAreaFilled(false);
        getContentPane().add(btnSalirhistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, 180, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hiatoriasldfwerfis.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirhistoria;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables


}
