/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ucr.ac.cr.tm2100.g3.laberinto1.Vista;

import java.awt.event.ActionListener;
import ucr.ac.cr.tm2100.g3.laberinto1.Modelo.Controlador;

/**
 *
 * @author carlo
 */
public class GUIInterfaz extends javax.swing.JFrame {

    /** Creates new form GUIInterfaz */
    public GUIInterfaz() {
        initComponents();
        
        setTitle("The Sin Of The Gods");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public void escuchar(ActionListener controlador){
  btnSalirInterfaz.addActionListener(controlador);
 
  }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalirInterfaz = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalirInterfaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnRegresar.jpg"))); // NOI18N
        btnSalirInterfaz.setText("Salir de Interfaz");
        btnSalirInterfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirInterfazActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 640, 170, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dibujo del laberinto.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirInterfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirInterfazActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirInterfazActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirInterfaz;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    



}
